apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-demo-dev
  namespace: suxess-it-admin
spec:
  destination:
    namespace: suxess-it-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/jkleinlercher/gitops-monitor-demo
    targetRevision: main
