apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-prod
  namespace: suxess-it-admin
spec:
  destination:
    namespace: suxess-it-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/jkleinlercher/gitops-helm-branch
    targetRevision: prod
    helm:
      valueFiles:
      - values-prod.yaml